spring:
  application:
    name: BankApiGate
  cloud:
    gateway:
      routes:
        - id: AdminService
          uri: http://localhost:8081
          predicates:
              - Path=/data/**,/login/**

        - id: AdminUI
          uri: http://localhost:8089
          predicates:
            - Path=/bui/**    
        - id: CustomersUI
          uri: http://localhost:8088
          predicates:
            - Path=/cui/**
        - id: TransactionService
          uri: http://localhost:8083
          predicates:
            - Path=/customer/**
          
        